export const actionTypes = {
    // Auth
    LOGIN: 'LOGIN',
    SIGNUP: 'SIGNUP',
    LOGOUT: 'LOGOUT',
    GET_ME: 'GET_ME',
    SET_WAREHOUSE_ADDRESS: "SET_WAREHOUSE_ADDRESS",

    // Product
    ADD_PRODUCT: "ADD_PRODUCT",
    GET_PRODUCT_CATEGORIES: "GET_PRODUCT_CATEGORIES",
}
